### ISSUE TITLE
Guano package no longer able to extract metadata

### ISSUE THREAD

**Issue by arky** [riggsd/guano-py#23]
Unfortunately, Guano module (1.0.14) no longer seems to be able to properly parse the files generated by Wildlife Acoustics devices such as SM4BAT.  

Error: 
```
Traceback (most recent call last):
  File "/test.py", line 11, in <module>
    print(g['Prefix'])
  File "/usr/local/lib/python3.10/dist-packages/guano.py", line 349, in __getitem__
    return self._md[namespace][key]
KeyError: ''
```

Attaching a test case for testing:
[testcase.zip](https://github.com/riggsd/guano-py/files/13197069/testcase.zip)

Module Version: 1.0.14
Python: 3.10

**Comment by arky** [comment]
The files I was testing with did not contain GUANO metadata.
